export { default as FarmIcon } from "./Farm";
export { default as GroupsIcon } from "./Groups";
export { default as HamburgerIcon } from "./Hamburger";
export { default as HamburgerCloseIcon } from "./HamburgerClose";
export { default as HomeIcon } from "./Home";
export { default as IfoIcon } from "./Ifo";
export { default as InfoIcon } from "./Info";
export { default as LogoIcon } from "./Logo";
export { default as MoonIcon } from "./Moon";
export { default as MoreIcon } from "./More";
export { default as NftIcon } from "./Nft";
export { default as PoolIcon } from "./Pool";
export { default as PredictionsIcon } from "./Predictions";
export { default as SunIcon } from "./Sun";
export { default as TeamBattleIcon } from "./TeamBattle";
export { default as TelegramIcon } from "./Telegram";
export { default as TicketIcon } from "./Ticket";
export { default as TradeIcon } from "./Trade";
export { default as TwitterIcon } from "./Twitter";
export { default as StakingIcon } from "./Staking";
export { default as ReferralsIcon } from "./Referrals";
export { default as StoreIcon } from "./Store";
export { default as AirdropIcon } from "./Airdrop";
export { default as BlindIcon } from "./Blind";
export { default as PoolNftIcon } from "./PoolNft";
export { default as MarketIcon } from "./Market";
export { default as RefIcon } from "./Ref";
export { default as GameIcon } from "./Game";
export { default as TShirtIcon } from "./TShirt";
export { default as MembershipIcon } from "./Membership";
export { default as DipoIcon } from "./DIPO";
export { default as RepoIcon } from "./Repo";
export { default as FacebookIcon } from "./Facebook";
export { default as YoutubeIcon } from "./Youtube";
export { default as VoteIcon } from "./Vote";
export { default as AffordableCapitalIcon } from "./AffordableCapitalIcon";
export { default as NewPortfolioIcon } from "./NewPortfolioIcon";
export { default as QuickSettlementIcon } from "./QuickSettlementIcon";
export { default as SecCompliantIcon } from "./SecCompliantIcon";
export { default as NtfMarketPlaceIcon } from "./NftMarketPlaceIcon"
export { default as DiscordIcon } from "./Discord"
export { default as GlobeIcon } from "./Globe"
export { default as EarnsIcon } from "./Earns"
export { default as PlusIcon } from "./Plus"
export { default as MinusIcon } from "./Minus"